---
output:
  pdf_document: default
  html_document: default
---
EOC thanks Deb Nichols, John Watanabe, Sophie Nichols-Watanabe, Bob Kelly, and the Dartmouth Coach. He says, “The concepts organized and presented in this work originated in 2015 during an evening banter in Norwich, Vermont, at Casa Nichols-Watanabe. While waiting for 6:30 PM, dinner time, the temperature rose to 39˚F - balmy weather for an April 23rd in Vermont. Amanda, my partner, Moni, our daughter, and I huddled around the familiar wood-burning stove that provided us with warmth, almost equaling our kind-hearted hosts. Bob Kelly’s amazing talk had taken place earlier in the day, at Silsby Hall, in Dartmouth’s Department of Anthropology. Dinner to celebrate it featured Big Fatty’s Barbecue, plus the usual delicious side dishes from colleagues. A couple of hours into the soiree, our daughter was tiring Sophie. Sophie is a sweet and energetic Labradoodle. According to John, tiring her was an unusual feat. I then overheard Bob ask Deb if anyone had written a straightforward paper that distilled Bayesian Statistics for archaeologists. In particular, Bob thought that archaeologists might benefit from understanding how Bayesian inference might differ from traditional statistics and why they may be necessary. In hindsight, in April 2015, Bayesian inference in archaeology was largely conducted in chronology construction. Although technical texts were available, others like Buck and Meson’s “On being a good Bayesian” (June 2015) and McElreath’s Statistical Rethinking (edition in 2016) were not in print. Bob’s was a reasonable question. I subsequently heard Deb call my name and say something along the lines of ‘you know who might be able to give you an answer - Erik.’ I immediately put down my brisket plate (which was very well done, by the way, great smoke ring and just falling apart at the mouth) and walked over to Bob and Deb. After a couple of minutes of laying out Bayesian inference, I realized that my thoughts were likely scattered and that I should stop talking before further confusing my audience. Bob and Deb were kind. I regrouped and boiled Bayesian statistics to two concepts: 1) the ability to speak in probabilities of our hypotheses and 2) a systematic framework to update them. Realizing that my thoughts would be clearer after properly organizing them, I thought I should write down a proper answer to Bob’s question. Those days, I commuted three days a week from Lebanon, NH, to teach statistics in Cambridge, MA, at Harvard’s Department of Statistics and my fellowship in Human Evolutionary Biology. The one-way ride started at 6 AM and ended two-and-a-half hours later. I would have time to put something rough but more coherent together – at least more coherent than what I had talked about at the party, I thought to myself. So, I wrote a draft of the foundation for the Monico story on the Dartmouth Coach while eating their complimentary popcorn. The initial characters were related to betting examples from horse racing. I had used this in the classroom, and I thought this might help readers interested in understanding Bayesian inference. Before arriving in South Station, I emailed them the draft. They were kind, thanked my effort, provided constructive commentary, and encouraged me to develop the story further. As a result, I continued to work on the example. Over time, I found colleagues knowledgeable on the subject matter, interested in its dissemination among archaeologists, and motivated to help carry this story forward. In August 2020, our son Nico was born, and so was the Monico story in its curret shape.”    

\newpage

# REFERENCES CITED
